version: '2'
services:
  goatron:
    build: .
    ports:
     - "8080:8080"
  mysql:
    image: "mysql:8.0.0"
    environment: 
      - MYSQL_USER=todo
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE=todo